#!/usr/bin/env ruby

require "securerandom"
require "base64"
require "dotenv/load"
require "scrypt"
require "star_adapter_mongodb"
require "star_adapter_json"

app unhype

db Star::DatabaseAdapter::MongoDB if ENV["ENV"] == "production"
db Star::DatabaseAdapter::Json if ENV["ENV"] == "development"

Star.load self, "models/users"
Star.load self, "models/tokens"
Star.load self, "models/tasklists"
Star.load self, "models/tasks"

router {
  Star.load self, "routes/prelude"
  Star.load self, "routes/tokens"
  Star.load self, "routes/users"
  Star.load self, "routes/tasklists"
}
