#!/usr/bin/env ruby

require "securerandom"
require "base64"
require "dotenv/load"
require "scrypt"

app unhype

case ENV["ENV"]
when "production"
  require "star_adapter_mongodb"
  db Star::DatabaseAdapter::MongoDB
else
  require "star_adapter_json"
  db Star::DatabaseAdapter::Json
end

Star.load self, "models/users"
Star.load self, "models/tokens"
Star.load self, "models/tasklists"
Star.load self, "models/tasks"

router {
  Star.load self, "routes/prelude"
  Star.load self, "routes/tokens"
  Star.load self, "routes/users"
  Star.load self, "routes/tasklists"
}
